export { default as ContactForm } from './contact-form/contact-form'
export { default as ContactLinks } from './contact-links/contact-links'
export { default as SocialLinks } from './social-links/social-links'
export { default as Details } from './details/details'
export { default as Form } from './form/form'
export { default as Modal } from './modal/modal'
