export { default as ArrowUp } from './arrow-up'
export { default as BehanceIcon } from './behance-icon'
export { default as HeartIcon } from './heart-icon'
export { default as InstagramIcon } from './instagram-icon'
export { default as LinkedinIcon } from './linkedin-icon'
