export { default as Home } from './home/home'
export { default as WebsiteImportance } from './website-importance/website-importance'
export { default as OurServices } from './our-services/our-services'
export { default as Methodologies } from './methodologies/methodologies'
export { default as LastCall } from './last-call/last-call'
