import Head from 'next/head'

import { Container } from '../styles/styles'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>Bem vindo a Octane!</Container>
    </div>
  )
}
