export { default as BehanceIcon } from './behance-icon'
export { default as Email } from './email'
export { default as InstagramIcon } from './instagram-icon'
export { default as LinkedinIcon } from './linkedin-icon'
export { default as Location } from './location'
export { default as OctaneGhost } from './octane-ghost'
export { default as Phone } from './phone'
export { default as CircleShape } from './circle-shape'
